name: "Setup tools"
description: "Install LLVM and some other tools"

inputs:
  llvm-file-url:
    description: "Pre-built archive URL (override when needed)"
    required: false
    default: "https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/clang+llvm-18.1.8-x86_64-linux-gnu-ubuntu-18.04.tar.xz"

runs:
  using: "composite"
  steps:
    - name: Install Tools
      uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3
      with:
        experimental: true

    - name: Install LLVM
      env:
        LLVM_FILE_URL: ${{ inputs.llvm-file-url }}
        LLVM_SKIP_INSTALL: "false"
      shell: bash
      run: .github/scripts/install-llvm.ts

    - name: Cache dependencies
      uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
