name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  LLVM_FILE_URL: https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/clang+llvm-18.1.8-x86_64-linux-gnu-ubuntu-18.04.tar.xz

jobs:
  format:
    name: Format
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Setup tools
        uses: ./.github/actions/setup-tools
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Check formatting
        run: mise tasks run format

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Setup tools
        uses: ./.github/actions/setup-tools
      - name: Install clippy
        run: rustup component add clippy
      - name: Check linting
        run: mise tasks run lint

  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Setup tools
        uses: ./.github/actions/setup-tools
      - name: Build
        run: mise tasks run build

  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Setup tools
        uses: ./.github/actions/setup-tools
      - name: Test
        run: mise tasks run test

  machete:
    name: Machete
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Setup tools
        uses: ./.github/actions/setup-tools
      - name: Install machete
        run: cargo install cargo-machete
      - name: Run machete
        run: cargo machete
